[package]
name = "test-util"
version.workspace = true
edition.workspace = true

[dependencies]
color-eyre.workspace = true
eyre.workspace = true
futures.workspace = true
thiserror.workspace = true
tracing-error.workspace = true
tracing-subscriber.workspace = true
